config/routes.rb
Shoppe::Engine.routes.draw do
    get 'attachment/:id/:filename.:extension' => 'attachments#show'

    resources :customers do
        post :search, :on => :collection
        resources :addresses
    end

    resources :product_categories do
        resources :localisations, controller: "product_category_localisations"
    end
    resources :products do
        resources :variants
        resources :localisations, controller: "product_localisations"
        collection do
            get :import
            post :import
        end
    end
    resources :orders do
        collection do
            post :search
        end
        member do
            post :accept
            post :reject
            post :ship
            get :despatch_note
        end
        resources :payments, :only => [:create, :destroy] do
            match :refund, :on => :member, :via => [:get, :post]
        end
    end
    resources :stock_level_adjustments, :only => [:index, :create]
    resources :delivery_services do
        resources :delivery_service_prices
    end
    resources :tax_rates
    resources :users
    resources :countries
    resources :attachments, :only => :destroy
    
    get 'settings'=> 'settings#edit'
    post 'settings' => 'settings#update'
    
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    match 'login/reset' => 'sessions#reset', :via => [:get, :post]
    
    delete 'logout' => 'sessions#destroy'
    get '/' => "dashboard#home"
end

Rails.application.routes.draw do
  mount Shoppe::Engine => '/admin'
  root "pages#index"
end

app/models/shoppe/address.rb
module Shoppe
  class Address < ActiveRecord::Base

    # An array of all the available types for an address
    TYPES = ["billing", "delivery"]

    # Set the table name
    self.table_name = "shoppe_addresses"
    
    # The customer which this address should be linked to
    # 
    # @return [Shoppe::Customer]
    belongs_to :customer, :class_name => "Shoppe::Customer"
    
    # The order which this address should be linked to
    # 
    # @return [Shoppe::Order]
    belongs_to :order, :class_name => "Shoppe::Order"

    # The country which this address should be linked to
    #
    # @return [Shoppe::Country]
    belongs_to :country, :class_name => "Shoppe::Country"

    # Validations
    validates :address_type, :presence => true, :inclusion => {:in => TYPES}
    validates :address1, :presence => true
    validates :address3, :presence => true
    validates :address4, :presence => true
    validates :postcode, :presence => true
    validates :country, :presence => true

    # All addresses ordered by their id asending
    scope :ordered, -> { order(:id => :desc)}
    scope :default, -> { where(default: true)}
    scope :billing, -> { where(address_type: "billing")}
    scope :delivery, -> { where(address_type: "delivery")}

    def full_address
      [address1, address2, address3, address4, postcode, country.try(:name)].join(", ")
    end

  end
end

app/models/shoppe/attachment.rb
module Shoppe
  class Attachment < ActiveRecord::Base

    # Set the table name
    self.table_name = "shoppe_attachments"

    # Mount the Carrierwave uploader
    mount_uploader :file, AttachmentUploader

    # Relationships
    belongs_to :parent, :polymorphic => true

    # Validations
    validates :file_name, :presence => true
    validates :file_type, :presence => true
    validates :file_size, :presence => true
    validates :file, :presence => true
    validates :token, :presence => true, :uniqueness => true

    # All attachments should have a token assigned to this
    before_validation { self.token = SecureRandom.uuid if self.token.blank? }

    # Set the appropriate values in the model
    before_validation do
      if self.file
        self.file_name = self.file.filename if self.file_name.blank?
        self.file_type = self.file.content_type if self.file_type.blank?
        self.file_size = self.file.size if self.file_size.blank?
      end
    end

    # Return the attachment for a given role
    def self.for(role)
      self.where(:role => role).first
    end

    # Return the path to the attachment
    def path
      file.url
    end

    # Is the attachment an image?
    def image?
      file_type.match(/\Aimage\//).present?
    end
    
  end
end

app/models/shoppe/country.rb
module Shoppe
  
  # The Shoppe::Country model stores countries which can be used for delivery & billing
  # addresses for orders.
  #
  # You can use the Shoppe::CountryImporter to import a pre-defined list of countries 
  # into your database. This automatically happens when you run the 'shoppe:setup' 
  # rake task.
  
  class Country < ActiveRecord::Base
    
    self.table_name = 'shoppe_countries'
    
    # All orders which have this country set as their billing country
    has_many :billed_orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order', :foreign_key => 'billing_country_id'
    
    # All orders which have this country set as their delivery country
    has_many :delivered_orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order', :foreign_key => 'delivery_country_id'
    
    # All countries ordered by their name asending
    scope :ordered, -> { order(:name => :asc) }
    
    # Validations
    validates :name, :presence => true
    
  end
end

app/models/shoppe/customer.rb
module Shoppe
  class Customer < ActiveRecord::Base

    self.table_name = "shoppe_customers"

    has_many :addresses, :dependent => :restrict_with_exception, :class_name => "Shoppe::Address"

    has_many :orders, :dependent => :restrict_with_exception, :class_name => "Shoppe::Order"

    # Validations
    validates :email, :presence => true, :uniqueness => true, :format => {:with => /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i}
    validates :phone, :presence => true, :format => {:with => /\A[\d\ \-x\(\)]{7,}\z/}

    # All customers ordered by their ID desending
    scope :ordered, -> { order(:id => :desc)}

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    def self.ransackable_attributes(auth_object = nil) 
      ["id", "first_name", "last_name", "company", "email", "phone", "mobile"] + _ransackers.keys
    end
  
    def self.ransackable_associations(auth_object = nil)
      []
    end

  end
end

app/models/shoppe/delivery_service.rb
module Shoppe
  class DeliveryService < ActiveRecord::Base
  
    self.table_name = 'shoppe_delivery_services'

    # Validations
    validates :name, :presence => true
    validates :courier, :presence => true
  
    # Orders which are assigned to this delivery service
    has_many :orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order'
    
    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, :dependent => :destroy, :class_name => 'Shoppe::DeliveryServicePrice'
  
    # All active delivery services
    scope :active, -> { where(:active => true)}
    
    # Returns a tracking URL for the passed order
    #
    # @param order [Shoppe::Order]
    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if self.tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!("{{consignment_number}}", CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!("{{delivery_postcode}}", CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!("{{billing_postcode}}", CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end

  end
end

app/models/shoppe/delivery_service_price.rb
module Shoppe
  class DeliveryServicePrice < ActiveRecord::Base

    # Set the table name
    self.table_name = 'shoppe_delivery_service_prices'
  
    include Shoppe::AssociatedCountries
  
    # The delivery service which this price belongs to
    belongs_to :delivery_service, :class_name => 'Shoppe::DeliveryService'
    
    # The tax rate which should be applied
    belongs_to :tax_rate, :class_name => "Shoppe::TaxRate"
    
    # Validations
    validates :code, :presence => true
    validates :price, :numericality => true
    validates :cost_price, :numericality => true, :allow_blank => true
    validates :min_weight, :numericality => true
    validates :max_weight, :numericality => true
  
    # All prices ordered by their price ascending
    scope :ordered, -> { order(:price => :asc) }
    
    # All prices which are suitable for the weight passed.
    #
    # @param weight [BigDecimal] the weight of the order
    scope :for_weight, -> weight { where("min_weight <= ? AND max_weight >= ?", weight, weight) }
  
  end
end

app/models/shoppe/order.rb
module Shoppe
  class Order < ActiveRecord::Base

    self.table_name = 'shoppe_orders'

    # Orders can have properties
    key_value_store :properties

    # Require dependencies
    require_dependency 'shoppe/order/states'
    require_dependency 'shoppe/order/actions'
    require_dependency 'shoppe/order/billing'
    require_dependency 'shoppe/order/delivery'

    # All items which make up this order
    has_many :order_items, :dependent => :destroy, :class_name => 'Shoppe::OrderItem', :inverse_of => :order
    accepts_nested_attributes_for :order_items, :allow_destroy => true, :reject_if => Proc.new { |a| a['ordered_item_id'].blank? }

    # All products which are part of this order (accessed through the items)
    has_many :products, :through => :order_items, :class_name => 'Shoppe::Product', :source => :ordered_item, :source_type => 'Shoppe::Product'

    # The order can belong to a customer
    belongs_to :customer, :class_name => 'Shoppe::Customer'
    has_many :addresses, :through => :customers, :class_name => "Shoppe::Address"

    # Validations
    validates :token, :presence => true
    with_options :if => Proc.new { |o| !o.building? } do |order|
      order.validates :email_address, :format => {:with => /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i}
      order.validates :phone_number, :format => {:with => /\A[\d\ \-x\(\)]{7,}\z/}
    end

    # Set some defaults
    before_validation { self.token = SecureRandom.uuid  if self.token.blank? }

    # Some methods for setting the billing & delivery addresses
    attr_accessor :save_addresses, :billing_address_id, :delivery_address_id

    # The order number
    #
    # @return [String] - the order number padded with at least 5 zeros
    def number
      id ? id.to_s.rjust(6, '0') : nil
    end

    # The length of time the customer spent building the order before submitting it to us.
    # The time from first item in basket to received.
    #
    # @return [Float] - the length of time
    def build_time
      return nil if self.received_at.blank?
      self.created_at - self.received_at
    end

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def customer_name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    # Is this order empty? (i.e. doesn't have any items associated with it)
    #
    # @return [Boolean]
    def empty?
      order_items.empty?
    end

    # Does this order have items?
    #
    # @return [Boolean]
    def has_items?
      total_items > 0
    end

    # Return the number of items in the order?
    #
    # @return [Integer]
    def total_items
      order_items.inject(0) { |t,i| t + i.quantity }
    end

    def self.ransackable_attributes(auth_object = nil)
      ["id", "billing_postcode", "billing_address1", "billing_address2", "billing_address3", "billing_address4", "first_name", "last_name", "company", "email_address", "phone_number", "consignment_number", "status", "received_at"] + _ransackers.keys
    end

    def self.ransackable_associations(auth_object = nil)
      []
    end

  end
end

app/models/shoppe/order/actions.rb
module Shoppe
  class Order < ActiveRecord::Base
    
    extend ActiveModel::Callbacks
    
    # These additional callbacks allow for applications to hook into other
    # parts of the order lifecycle.
    define_model_callbacks :confirmation, :acceptance, :rejection
  
    # This method should be called by the base application when the user has completed their 
    # first round of entering details. This will mark the order as "confirming" which means
    # the customer now just must confirm.
    #
    # @param params [Hash] a hash of order attributes
    # @return [Boolean]
    def proceed_to_confirm(params = {})
      self.status = 'confirming'
      if self.update(params)
        true
      else
        false
      end
    end
  
    # This method should be executed by the application when the order should be completed
    # by the customer. It will raise exceptions if anything goes wrong or return true if
    # the order has been confirmed successfully
    #
    # @return [Boolean]
    def confirm!
      no_stock_of = self.order_items.select(&:validate_stock_levels)
      unless no_stock_of.empty?
        raise Shoppe::Errors::InsufficientStockToFulfil, :order => self, :out_of_stock_items => no_stock_of
      end
    
      run_callbacks :confirmation do
        # If we have successfully charged the card (i.e. no exception) we can go ahead and mark this
        # order as 'received' which means it can be accepted by staff.
        self.status = 'received'
        self.received_at = Time.now
        self.save!

        self.order_items.each(&:confirm!)

        # Send an email to the customer
        deliver_received_order_email
      end
    
      # We're all good.
      true
    end
  
    # Mark order as accepted
    #
    # @param user [Shoppe::User] the user who carried out this action    
    def accept!(user = nil)
      run_callbacks :acceptance do
        self.accepted_at = Time.now
        self.accepter = user if user
        self.status = 'accepted'
        self.save!
        self.order_items.each(&:accept!)
        deliver_accepted_order_email
      end
    end
  
    # Mark order as rejected
    #
    # @param user [Shoppe::User] the user who carried out the action
    def reject!(user = nil)
      run_callbacks :rejection do
        self.rejected_at = Time.now
        self.rejecter = user if user
        self.status = 'rejected'
        self.save!
        self.order_items.each(&:reject!)
        deliver_rejected_order_email
      end
    end

    def deliver_accepted_order_email
      Shoppe::OrderMailer.accepted(self).deliver_now
    end

    def deliver_rejected_order_email
      Shoppe::OrderMailer.rejected(self).deliver_now
    end

    def deliver_received_order_email
      Shoppe::OrderMailer.received(self).deliver_now
    end
    
  end
end

app/models/shoppe/order/states.rb
module Shoppe
  class Order < ActiveRecord::Base
    
    # An array of all the available statuses for an order
    STATUSES = ['building', 'confirming', 'received', 'accepted', 'rejected', 'shipped']
    
    # The Shoppe::User who accepted the order
    #
    # @return [Shoppe::User]
    belongs_to :accepter, :class_name => 'Shoppe::User', :foreign_key => 'accepted_by'
    
    # The Shoppe::User who rejected the order
    #
    # @return [Shoppe::User]
    belongs_to :rejecter, :class_name => 'Shoppe::User', :foreign_key => 'rejected_by'
    
    # Validations
    validates :status, :inclusion => {:in => STATUSES}
    
    # Set the status to building if we don't have a status
    after_initialize  { self.status = STATUSES.first if self.status.blank? }
    
    # All orders which have been received
    scope :received, -> {where("received_at is not null")}
    
    # All orders which are currently pending acceptance/rejection
    scope :pending, -> { where(:status => 'received') }
    
    # All ordered ordered by their ID desending
    scope :ordered, -> { order(:id => :desc)}
    
    # Is this order still being built by the user?
    #
    # @return [Boolean]
    def building?
      self.status == 'building'
    end
  
    # Is this order in the user confirmation step?
    #
    # @return [Boolean]
    def confirming?
      self.status == 'confirming'
    end
  
    # Has this order been rejected?
    #
    # @return [Boolean]
    def rejected?
      !!self.rejected_at
    end
  
    # Has this order been accepted?
    #
    # @return [Boolean]
    def accepted?
      !!self.accepted_at
    end
  
    # Has the order been received?
    #
    # @return [Boolean]
    def received?
      !!self.received_at?
    end
  
    
  end
end

app/models/shoppe/product/product_attributes.rb
module Shoppe
  class Product < ActiveRecord::Base
  
    # Product attributes for this product
    has_many :product_attributes, -> { order(:position) }, :class_name => 'Shoppe::ProductAttribute'
  
    # Used for setting an array of product attributes which will be updated. Usually
    # received from a web browser.
    attr_accessor :product_attributes_array
    
    # After saving automatically try to update the product attributes based on the
    # the contents of the product_attributes_array array.
    after_save do
      if product_attributes_array.is_a?(Array)
        self.product_attributes.update_from_array(product_attributes_array)
      end
    end
  
  end
end

app/views/shoppe/customers/_addresses.html.haml
.addresses
  .table
    %table.data
      %thead
        %tr
          %th Type
          %th Default
          %th Address
          %th
      %tbody
        - if @addresses.empty?
          %tr.empty
            %td{:colspan => 4} No addresses to display.
        - else
          - for address in @addresses
            %tr
              %td= address.address_type.capitalize
              %td= boolean_tag address.default
              %td= address.full_address
              %td= link_to "Edit", edit_customer_address_path(@customer, address)

app/views/shoppe/customers/_form.html.haml
= form_for @customer do |f|
  = f.error_messages

  = field_set_tag "Customer Information" do
    .splitContainer
      %dl.third
        %dt= f.label :first_name
        %dd= f.text_field :first_name, :class => "text focus"
      %dl.third
        %dt= f.label :last_name
        %dd= f.text_field :last_name, :class => "text"
      %dl.third
        %dt= f.label :company
        %dd= f.text_field :company, :class => "text"
    .splitContainer
      %dl.third
        %dt= f.label :email
        %dd= f.text_field :email, :class => "text"
      %dl.third
        %dt= f.label :phone
        %dd= f.text_field :phone, :class => "text"
      %dl.third
        %dt= f.label :mobile
        %dd= f.text_field :mobile, :class => "text"

  %p.submit
    - unless @customer.new_record?
      %span.right= link_to "Delete", @customer, :class => 'button purple', :method => :delete, :data => {:confirm => "Are you sure you wish to remove this product?"}
    = f.submit :class => 'button green', data: {disable_with: (@customer.new_record? ? "Creating Customer..." : "Updating Customer...")}
    = link_to "Cancel", :customers, :class => 'button'

app/views/shoppe/customers/_search_form.html.haml
.customerSearch{:style => action_name == 'search' ? "display:block" : ''}
  = search_form_for @query, :url => search_customers_path, :html => { :method => :post } do |f|
    %dl.left
      %dt= f.label :first_name_or_last_name_or_company_cont, "First or Last Name"
      %dd= f.text_field :first_name_or_last_name_or_company_cont
      %dt= f.label :company_cont, "Company"
      %dd= f.text_field :company_cont
    %dl.right
      %dt= f.label :email_cont, "Email Address"
      %dd= f.text_field :email_cont
      %dt= f.label :phone_cont, "Phone Number"
      %dd= f.text_field :phone_cont
      %dd= f.submit "Search", :class => 'button green button'

app/views/shoppe/customers/edit.html.haml
- @page_title = "Customers"
= content_for :header do
  %p.buttons= link_to "Back to customer list", :customers, :class => 'button'
  %h2.users Customers
= render "form"

app/views/shoppe/customers/index.html.haml
- @page_title = "Customers"

= content_for :header do
  %p.buttons
    = link_to "New Customer", :new_customer, class: "button green"
    = link_to "Search Customers", '#', class: 'button', rel: "searchCustomers"
  %h2.users Customers

= render "search_form"

.table
  %table.data
    %thead
      %tr
        %th Name
        %th Company
        %th Email
        %th Phone
        %th Mobile
    %tbody
      - if @customers.empty?
        %tr.empty
          %td{colspan: 5} No customers to display.
      - else
        - for customer in @customers
          %tr
            %td= link_to customer.full_name, customer
            %td= link_to customer.company, customer
            %td= customer.email
            %td= customer.phone
            %td= customer.mobile
= paginate @customers

app/views/shoppe/customers/new.html.haml
- @page_title = "Customers"
= content_for :header do
  %p.buttons= link_to "Back to customer list", :customers, :class => 'button'
  %h2.users Customers
= render "form"

app/views/shoppe/customers/show.html.haml
- @page_title = "Customer - #{@customer.name}"
= content_for :header do
  %p.buttons
    = link_to "New Address", [:new, @customer, :address], class: "button"
    = link_to "Edit", [:edit, @customer], class: "button"
  %h2.users
    Customer - #{@customer.name}

#customer
  .details
    .left
      %dl
        %dt Name
        %dd= @customer.full_name
        %dt Company
        %dd= @customer.company.blank? ? '-' : @customer.company
    .right
      %dl
        %dt Email Address
        %dd= mail_to @customer.email
        %dt Telephone
        %dd= @customer.phone
        %dt Mobile
        %dd= @customer.mobile

  = field_set_tag "Addresses", :class => 'padded' do
    = render "addresses"

  = field_set_tag t('shoppe.orders.orders'), :class => 'padded' do
    .table
      %table.data
        %thead
          %tr
            %th= t('shoppe.orders.number')
            %th= t('shoppe.orders.status')
            %th= t('shoppe.orders.products')
            %th= t('shoppe.orders.total')
            %th= t('shoppe.orders.payment')
        %tbody
          - if @orders.empty?
            %tr.empty
              %td{:colspan => 6}= t('shoppe.orders.no_orders')
          - else
            - for order in @orders
              %tr
                %td= link_to order.number, order
                %td= status_tag order.status
                %td
                  %ul
                    - for item in order.order_items
                      %li #{item.quantity} x #{item.ordered_item.full_name}
                %td= number_to_currency order.total
                %td= boolean_tag order.paid_in_full?, nil, :true_text => number_to_currency(order.amount_paid), :false_text => number_to_currency(order.amount_paid)